import '../node_modules/@fortawesome/fontawesome-pro-webfonts/css/fontawesome.css';
import '../node_modules/@fortawesome/fontawesome-pro-webfonts/css/fa-solid.css';
import '../node_modules/@fortawesome/fontawesome-pro-webfonts/css/fa-regular.css';
import '../node_modules/@fortawesome/fontawesome-pro-webfonts/css/fa-light.css';
import '../node_modules/@fortawesome/fontawesome-pro-webfonts/css/fa-brands.css';
import './css/awinTheme.css';
import '../node_modules/jquery/dist/jquery.js';
import '../node_modules/bootstrap/dist/js/bootstrap.js';
import './js/styleguide.js';
